### ISSUE TITLE
Control PCB 4.0

### ISSUE THREAD

**Issue by ao-david** [ausocean/rig#3]
# Background
We would like to add additional features to the PCB in order to have more diagnostic tools at our disposal, as well as improve fabrication ease and usability. This change will require an upgrade in our MCU, likely moving to an ESP32 system. The advantage of an ESP32 over an ESP8266 is the ability to have more ADCs available. This will allow us to measure more analog voltages such as voltage outputs after relays, and current flow in the system.

# Features

These are the current proposed feature upgrades over the v3.0 version (PoE capable version)

## High Priority

- Voltage sensing after relay to determine relay failure
- Currrent sensing into the PCB to determine total power consumption (Voltage is already measured)
- Screw terminals for switch power

## Low Priority

- Debug LEDs
- Use SMD components where applicable for cheaper prices, and decrease manual manufacturing

# Interface

The proposed interface with other components within the system as as follows

## Inputs
- Screw terminals for 24V power input from Solar Charge Controller
- microUSB port for 5V power from Solar Charge Controller 5V output (could use USB C, but requires additional circuitry that is unnecessary)
- 4x1 block input for DHT sensor (potentially JST, but explore other options)
- Sea Surface Temperature (JST)
- 3 RJ45 PoE inputs for Peripherals

## Outputs
- USB-A 5V to Router
- Screw terminal 5V to switch
- 3 RJ45 data outputs to switch
- 2x1 output for NavLight (potentially JST)

**Comment by scruzin** [comment]
PTAL at Issue #4 @ao-david 

This would require another analog port, which is another reason to move to the ESP32.
